# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# TODO(setup): Typically the course number, "DEPT XXX". it appears on nearly every page. Keep it short. :)
title: Data 6
# TODO:(setup): This should be the extended title of your course. e.g. "Introduction to Data Science"
tagline: Introduction to Computational Thinking with Data
description: A modern, highly customizable, responsive Jekyll template for course websites
# TODO(template): this should be built from the staff list...
author: Edwin Vargas Navarro
# You should use either light or dark as the theme.
color_scheme: light

# TODO(setup): Set this to the semester, e.g. /sp24, (faXX / spXX / suXX / wiXX )
baseurl: '/su25' # the subpath of your site, which should just be the semester.
# TODO(setup): Set this to your course's domain
url: 'https://www.data6.org' # the hostname & protocol for your site, e.g. http://example.com

# Course variables
# Course variables can appear in various places around the website, if something isn't used leave it blank.
# TODO(setup): Set all of these course variables
course: Data 6
course_email: jedwin321@berkeley.edu
gradescope_course_id: 835871 # you can find this in the Gradescope URL after /courses
bcourses_course_id: 1538208 # Same as above, but for bCourses. Leave blank if not in use...
ed_course_id: 64093 # Again, same as above.
sememster: su25 # set for the current seemester
# This should be one of eecs, dsus, stat
# (Future) This will control some footer text, and later custom styling.
course_department: dsus
logo: "/data6.png"
current_week: 1-introduction-to-python
# This should be the page of all class archives
# Typically just / for DS courses (with a visible index page), or /archives if you're hosting your own, or a link to the inst.eecs page
# If you have no archive page, comment this line out or leave blank.
class_archive_path: /

# TODO(setup): Set these auxiliary links as you wish - they show up on the top right
aux_links:
  # TODO(template): Move this to be built-in.
  # OH Queue:
  #   - 'https://oh.data8.org/'
  # Textbook:
  #   - 'https://inferentialthinking.com/chapters/intro.html'
  # Extensions:
  #   - 'https://docs.google.com/forms/d/e/1FAIpQLSc2CSE_Ie_TR0r7lV7-JX0zNagoJ08t-EAK48iCAc3rVgHIXw/viewform'

# Collections for website data
collections:
  staffers:
    sort_by: name
  modules:
  schedules:
  announcements:
  labs:
    output: true
    permalink: /:collection/:path/
  hw:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: labs
    values:
      layout: lab
      nav_exclude: true
  - scope:
      path: ''
      type: hw
    values:
      layout: hw
      nav_exclude: true
  - scope:
      path: ''
      type: projects
    values:
      layout: project
      nav_exclude: true
  - scope:
      path: '_staffers'
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

######################################################################
# Just the Docs / Berkeley Class Site Common Config
# Options below here will likely not need to be configured..
######################################################################
# TODO(template): CSS compilations. Handle warnings...
sass:
  style: expanded
  sass_dir: _sass
  sourcemap: always
  quiet_deps: true
  verbose: false

# The sitemap **must** be enabled. It's published as /baseurl/sitemap.xml
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Theme settings
theme: just-the-docs
search_enabled: true
heading_anchors: true
permalink: pretty

## Footer Content.
# You should probably not change these, but may add to footer_content if necessary.
# Replace `true` with any additional HTML that you would like to add.
# Footer *must* included the accessibility text defined in footer_custom.html
footer_content: true
back_to_top: true
back_to_top_text: "Back to Top"
last_edit_timestamp: true
last_edit_time_format: '%m %d, %Y at %H:%M'

# Compilation settings used by compress-html plugin:
# https://github.com/penibelst/jekyll-compress-html/tree/v3.2.0?tab=readme-ov-file
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Native Jeykll build options
# You likely shouldn't need to touch these, but they are documented here just in case.
# https://jekyllrb.com/docs/configuration/options/

# This makes it easier when pushing to a static directory.
# The default false removes files in that directory, which is useful for when you unpublish pages.
# keep_files: false

# Likely not necessary, but a google default for Berkeley
timezone: America/Los_Angeles

# Note: dotfiles are excluded by default. .htaccess is included as a common case.
include:
  - LICENSE
  - .htaccess
  - robots.txt

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - CONTRIBUTING.md
  - tmp/
  - spec/
  - docs/
  - node_modules/

links:
  hw:
    hw01: "[HW 01: Introduction to Python](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Fhw%2Fhw01%2Fhw01.ipynb)"
    hw02: "Table Methods and Functions"
    hw03: "Advanced Table Methods and Visualizations"
    hw04: "Control, Iterations, Strings"

  lab:
    lab01: "[Lab 01: Using Jupyter Notebooks](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flab%2Flab01%2Flab01.ipynb)"
    lab02: "[Lab 02: Tables and Data Manipulation](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flab%2Flab02%2Flab02.ipynb)"
    lab03: "Lab 03: Functions" # from Fa24 with no autograder, added to SU25
    lab04: "Lab 04: Tables"
    lab05: "Lab 05: Introduction to Visualization Methods"
    lab06: "Lab 06: Visualizing Two Numerical Variables and Randomness" #updated
    lab07: "Lab 07: Functions, Control, Iteration" # updated
    lab08: "Lab 08: Dictionaries" # From SU23/SU24
    lab09: "Lab 09: APIs and Prompt Engineering" # new
    lab10: "Lab 10: TF-IDF, Cohen's Kappa, and Macro F1" # new

  wksht:
    wksht01: "[Worksheet](https://drive.google.com/file/d/1b1jM2bJnVGVDEqM88ZBS50BUi5H1ASPy/view?usp=sharing) &#8226; [Slides](https://docs.google.com/presentation/d/1jNPxnBSJXDtQ0hzsZCU_PVf2HtfbLHnmGbCpj9NmvMM/edit?usp=sharing)"
    wksht02: "[Worksheet](https://drive.google.com/file/d/19JleiiKJr075wzHQkRmZLGKLHnG68TUb/view?usp=sharing) &#8226; [Slides](https://docs.google.com/presentation/d/1GfNti3gkxMXExtaTGDc3iCVrUyQxCk0PSyD2iQz9iz8/edit?usp=sharing)"
    wksht03: "[Worksheet](https://drive.google.com/file/d/1feRlVNlrkUduEwoZ2IiL8qYGmZv0yP-p/view?usp=sharing) &#8226; [Slides](https://docs.google.com/presentation/d/1mCPG0GiS-zjNmUY-FmLyQSItPXoQ_PP4Lk0DfuFRXwk/edit?usp=sharing)"
    wksht04: "Worksheet 04"
    wksht05: "Worksheet 05"
  
  reading:
    reading01: "Assignment"
    reading02: "Assignment"
    reading03: "Assignment"
    reading04: "Assignment"
    reading05: "Assignment"
  
  survey:
    survey00: "[Pre-Semester Survey](https://docs.google.com/forms/d/e/1FAIpQLSe9asLtMi_gYKKuAMaJ3unLN6FtVBm-e2VIm_W8FFF52ALCGw/viewform?usp=sharing&ouid=103402950542338937761)"
    survey01: "[Week 01 Survey](https://docs.google.com/forms/d/e/1FAIpQLSe4XO5XgXcw9QCc4eRyln2m2u27qCcjJ7HW-mVLA-eF4eYBwA/viewform?usp=sharing&ouid=103402950542338937761)"
    survey02: "Week 02 Survey"
    survey03: "Week 03 Survey"
    survey04: "Week 04 Survey"
    survey05: "Week 05 Survey"
  proj:
    part1: "Final Project Part 1"
    part2: "Final Project Part 2"

  lec:
    demo:
      demo01: 
      demo01-blank: 
      demo02: "&#8226; Demo"
      demo02-blank: "&#8226; [Blank Demo](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flectures%2Flec02%2Flec02-blank.ipynb)"
      demo03: "&#8226; Demo"
      demo03-blank: "&#8226; [Blank Demo](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flectures%2Flec03%2Flec03-blank.ipynb)"
      demo04: "&#8226; Demo"
      demo04-blank: "&#8226; [Blank Demo](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flectures%2Flec04%2Flec04-blank.ipynb)"
      demo05: ""
      demo05-blank: ""
      demo06: "&#8226; Demo"
      demo06-blank: "&#8226; [Blank Demo](https://datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-6-berkeley%2Fmaterials-su25&branch=main&urlpath=tree%2Fmaterials-su25%2Flectures%2Flec06%2Flec06-blank.ipynb)"
      demo07: "&#8226; Demo"
      demo07-blank: "&#8226; Blank Demo"
      demo08: "&#8226; Demo"
      demo08-blank: "&#8226; Blank Demo"
      demo09: "&#8226; Demo"
      demo09-blank: "&#8226; Blank Demo"
      demo10: "&#8226; Demo"
      demo10-blank: "&#8226; Blank Demo"
      demo11: "&#8226; Demo"
      demo11-blank: "&#8226; Blank Demo"
      demo12: "&#8226; Demo"
      demo12-blank: "&#8226; Blank Demo"
      demo13: "&#8226; Demo"
      demo13-blank: "&#8226; Blank Demo"
      demo14: "&#8226; Demo"
      demo14-blank: "&#8226; Blank Demo"
      demo15: "&#8226; Demo"
      demo15-blank: "&#8226; Blank Demo"
      demo16: "&#8226; Demo"
      demo16-blank: "&#8226; Blank Demo"
      demo17: "&#8226; Demo"
      demo17-blank: "&#8226; Blank Demo"
      demo18: "&#8226; Demo"
      demo18-blank: "&#8226; Blank Demo"
      demo19: "&#8226; Demo"
      demo19-blank: "&#8226; Blank Demo"
      demo20: "&#8226; Demo"
      demo20-blank: "&#8226; Blank Demo"
      demo21: "&#8226; Demo"
      demo21-blank: "&#8226; Blank Demo"
      demo22: "&#8226; Demo"
      demo22-blank: "&#8226; Blank Demo"
      demo23: "&#8226; Demo"
      demo23-blank: "&#8226; Blank Demo"
      demo24: "&#8226; Demo"
      demo24-blank: "&#8226; Blank Demo"
      demo25: "&#8226; Demo"
      demo25-blank: "&#8226; Blank Demo"
      demo26: "&#8226; Demo"
      demo26-blank: "&#8226; Blank Demo"
      demo27: "&#8226; Demo"
      demo27-blank: "&#8226; Blank Demo"
      demo28: "&#8226; Demo"
      demo28-blank: "&#8226; Blank Demo"
      demo29: "&#8226; Demo"
      demo29-blank: "&#8226; Blank Demo"
      demo30: "&#8226; Demo"
      demo30-blank: "&#8226; Blank Demo"
      demo31: "&#8226; Demo"
      demo31-blank: "&#8226; Blank Demo"
      demo32: "&#8226; Demo"
      demo32-blank: "&#8226; Blank Demo"
    slides:
      slide01: "[Slides](https://docs.google.com/presentation/d/1z0cir2IWCyai3lnxoel1Ly0zYltaPOO006EGFHTkaT4/edit?usp=sharing)"
      slide02: "[Slides](https://docs.google.com/presentation/d/1FJEBbZyclKvTsvTjzKG8S_Kr9xI738AT75Yq2W-mb7U/edit?usp=sharing)"
      slide03: "[Slides](https://docs.google.com/presentation/d/1s-cpllzfqP2843I2Ve7rhBwK9KqEX7TeEFzTSSmFccQ/edit?usp=sharing)"
      slide04: "[Slides](https://docs.google.com/presentation/d/10nAwX2_i4b66XVMla7CahCARkLSa4jR14PLhof0GGu4/edit?usp=sharing)"
      slide05: "[Slides](https://docs.google.com/presentation/d/19dw3wet1QWoJJOKzBmPcCHMMTp5dmL_qha8hM4kqcJI/edit?usp=sharing)"
      slide06: "[Slides](https://docs.google.com/presentation/d/15sCA0QbtmzFT4VOuOqgVZpDCA6-Z9aHa8GyVl5vS4YY/edit?usp=sharing)"
      slide07: "Slides"
      slide08: "Slides"
      slide09: "Slides"
      slide10: "Slides"
      slide11: "Slides"
      slide12: "Slides"
      slide13: "Slides"
      slide14: "Slides"
      slide15: "Slides"
      slide16: "Slides"
      slide17: "Slides"
      slide18: "Slides"
      slide19: "Slides"
      slide20: "Slides"
      slide21: "Slides"
      slide22: "Slides"
      slide23: "Slides"
      slide24: "Slides"
      slide25: "Slides"
      slide26: "Slides"
      slide27: "Slides"
      slide28: "Slides"
      slide29: "Slides"
      slide30: "Slides"
      slide31: "Slides"
      slide32: "Slides"